### ISSUE TITLE
Support Pdf and other file types

### ISSUE THREAD

**Issue by timfam** [orionjs/file-attribute#1]
I can't upload pdf or words documents, ```isImage``` prevents that. What is the best way around this? And the helper that controls this is in filesystem package so we need to expand filesystem too to support all extension types

**Comment by nicolaslopezj** [comment]
Are you sure you can't? Which version are you using? I just tried and it works

**Comment by timfam** [comment]
Sorry about this, I updated to new version and it works, maybe it was my setup.
